# Stage 1: Build
FROM node:20-alpine AS stage-1
WORKDIR /app
COPY package*.json ./
RUN npm install && npm cache clean --force
COPY . .
RUN npm run build

# Stage 2: Serve the built files
FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=stage-1 /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]